name: CI - WebUI

on: [pull_request, push]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Check
    runs-on: ubuntu-slim

    defaults:
      run:
        working-directory: src/webui/www

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup nodejs
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 'lts/*'

      - name: Install tools
        run: |
          npm install
          npm ls
          echo "::group::npm ls --all"
          npm ls --all
          echo "::endgroup::"

      - name: Run tests
        run: npm test

      - name: Lint code
        if: ${{ !cancelled() }}
        run: npm run lint

      - name: Format code
        if: ${{ !cancelled() }}
        run: |
          npm run format
          git diff --exit-code
